name: Publish CLI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          repository: 'xc2/maestro'
          ref: xc2-fix

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Setup version
        id: versions
        run: echo "suffix=fork$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Update Release Info
        run: |
          sed -i 's/^\(CLI_VERSION=.*\)$/\1-${{ steps.versions.outputs.suffix }}/' maestro-cli/gradle.properties
          sed -i '/release\s*{/,/changelog\s*{/ {
              s/repoOwner\.set("mobile-dev-inc")/repoOwner.set("xc2")/
              s/name\.set("maestro")/name.set("maestro")/
            }' maestro-cli/build.gradle.kts
          sed -i '/repoTap\s*{/,/dependencies\s*{/ {
              s/repoOwner\.set("mobile-dev-inc")/repoOwner.set("xc2")/
              s/name\.set("homebrew-tap")/name.set("homebrew-maestro")/
            }' maestro-cli/build.gradle.kts
          cat maestro-cli/gradle.properties
          cat maestro-cli/build.gradle.kts

      - name: Publish CLI
        run: ./gradlew :maestro-cli:jreleaserFullRelease --no-daemon --no-parallel
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print jReleaser log
        if: always()
        run: cat maestro-cli/build/jreleaser/trace.log
